version: "3.8"

services:

  data_s:
    build:
      context: ./sde-rest-advanced-data
    ports:
      - 8081:80
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    volumes:
      - /www/node_modules
      - ./sde-rest-advanced-data:/www


  api_s:
    build:
      context: ./sde-rest-advanced-api
    ports:
      - 8082:80
    networks:
      app_net:
        ipv4_address: 172.16.238.20
    volumes:
      - /www/node_modules
      - ./sde-rest-advanced-api:/www

  frontend_s:
    build:
      context: ./sde-rest-advanced-frontend
    ports:
      - 8083:4200
    networks:
      app_net:
        ipv4_address: 172.16.238.30
    volumes:
      - /www/node_modules
      - ./sde-rest-advanced-frontend:/www

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
